<!DOCTYPE html>
<html>
<head>
    <title>Create Payment Receipt PDF</title>
</head>
<body>

<h2>Generate Payment Receipt</h2>

<input type="text" id="reference" placeholder="Reference Number"><br><br>
<input type="text" id="customerName" placeholder="Customer Name"><br><br>
<input type="text" id="vehicleNumber" placeholder="Vehicle Number"><br><br>
<input type="text" id="contactNumber" placeholder="Contact Number"><br><br>
<input type="number" id="amount" placeholder="Payment Amount"><br><br>

<button onclick="generateAndSavePDF()">Generate PDF & Save</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

<script>
async function generateAndSavePDF() {
    const reference = document.getElementById("reference").value;
    const customerName = document.getElementById("customerName").value;
    const vehicleNumber = document.getElementById("vehicleNumber").value;
    const contactNumber = document.getElementById("contactNumber").value;
    const amount = document.getElementById("amount").value;

    if (!reference || !customerName) {
        alert("Please enter reference number and customer name");
        return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Airport Parking Payment Receipt", 20, 20);

    doc.setFontSize(12);
    doc.text("Reference Number: " + reference, 20, 40);
    doc.text("Customer Name: " + customerName, 20, 50);
    doc.text("Vehicle Number: " + vehicleNumber, 20, 60);
    doc.text("Contact Number: " + contactNumber, 20, 70);
    doc.text("Payment Amount: Rs. " + amount, 20, 80);
    doc.text("Payment Status: Paid", 20, 90);
    doc.text("Generated By: " + customerName, 20, 100);
    doc.text("Generated Date: " + new Date().toLocaleString(), 20, 110);

    const pdfBlob = doc.output("blob");

    const formData = new FormData();
    formData.append("reference", reference);
    formData.append("generated_by", customerName);
    formData.append("pdf", pdfBlob, "receipt.pdf");

    const response = await fetch("api/save_payment_receipt.php", {
        method: "POST",
        body: formData
    });

    const result = await response.json();

    if (result.status === "success") {
        alert("PDF generated and saved successfully");
        doc.save(result.receipt_no + ".pdf");
    } else {
        alert(result.message);
    }
}
</script>

</body>
</html>