<?php
session_start();
require_once __DIR__ . '/db_connect.php';
require_once dirname(__DIR__, 2) . '/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

header('Content-Type: application/json');
date_default_timezone_set('Asia/Colombo');

$bookingId = $_POST['id'] ?? null;
$requestedAmount = isset($_POST['amount']) ? (float)$_POST['amount'] : 0;
$updatedTotalPrice = isset($_POST['updated_total_price']) ? (float)$_POST['updated_total_price'] : 0;
$editedEndDate = $_POST['edited_end_date'] ?? null;
$loggedInUserId = $_SESSION['user_id'] ?? null;

if (!$bookingId) {
    echo json_encode(['success' => false, 'message' => 'Invalid booking ID']);
    exit;
}

if (!$loggedInUserId) {
    echo json_encode(['success' => false, 'message' => 'User not logged in']);
    exit;
}

function safeFolderName($name) {
    $name = trim($name);
    $name = preg_replace('/[^A-Za-z0-9\-_]/', '_', $name);
    return $name ?: 'unknown_reference';
}

function h($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

try {
    $conn->beginTransaction();

    $stmt = $conn->prepare("SELECT * FROM reserved_slots WHERE id = ?");
    $stmt->execute([$bookingId]);
    $b = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$b) {
        $conn->rollBack();
        echo json_encode(['success' => false, 'message' => 'Booking not found']);
        exit;
    }

    $paidStmt = $conn->prepare("
        SELECT COALESCE(SUM(payment_amount), 0) AS total_paid
        FROM payment_receipts
        WHERE reserved_slot_id = ?
    ");
    $paidStmt->execute([$bookingId]);
    $paidRow = $paidStmt->fetch(PDO::FETCH_ASSOC);
    $totalPaidSoFar = (float)($paidRow['total_paid'] ?? 0);

    $balanceAmount = $updatedTotalPrice - $totalPaidSoFar;

    if ($balanceAmount <= 0) {
        $conn->rollBack();
        echo json_encode(['success' => false, 'message' => 'No balance amount to collect']);
        exit;
    }

    if (abs($requestedAmount - $balanceAmount) > 0.01) {
        $requestedAmount = $balanceAmount;
    }

    $customerName = $b['name'] ?? '';
    $contactNumber = $b['whatsapp_number'] ?? '';
    $vehicleNumber = $b['vehicle_number'] ?? '';
    $parkingLocation = $b['slot_number'] ?? '';
    $referenceNumber = $b['reference_number'] ?? ('BOOKING_' . $bookingId);
    $realArrivedAt = date('Y-m-d H:i:s');

    $startDate = !empty($b['start_date']) ? date('Y-m-d h:i A', strtotime($b['start_date'])) : '';
    $endDate = !empty($editedEndDate)
        ? date('Y-m-d h:i A', strtotime($editedEndDate))
        : (!empty($b['end_date_edited'])
            ? date('Y-m-d h:i A', strtotime($b['end_date_edited']))
            : (!empty($b['end_date']) ? date('Y-m-d h:i A', strtotime($b['end_date'])) : ''));

    $expectedParkingDuration = $startDate . ' to ' . $endDate;

    $newTotalPaid = $totalPaidSoFar + $balanceAmount;
    $paymentStatus = ($newTotalPaid >= $updatedTotalPrice) ? 'Paid Fully' : 'Partially Paid';

    $receiptNo = 'RCPT-' . date('YmdHis') . '-' . $bookingId;

    $updateStmt = $conn->prepare("
        UPDATE reserved_slots
        SET payment_status = ?,
            payment_updated_by = ?,
            total_price_final = ?,
            end_date_edited = ?
        WHERE id = ?
    ");
    $updateStmt->execute([
        $paymentStatus,
        $loggedInUserId,
        $updatedTotalPrice,
        !empty($editedEndDate) ? date('Y-m-d H:i:s', strtotime($editedEndDate)) : null,
        $bookingId
    ]);

    $insertStmt = $conn->prepare("
        INSERT INTO payment_receipts (
            reserved_slot_id,
            receipt_no,
            payment_amount,
            payment_status,
            generated_at,
            generated_by,
            customer_name,
            contact_number,
            vehicle_number,
            parking_location,
            expected_parking_duration,
            real_arrived_at
        ) VALUES (?, ?, ?, ?, NOW(), ?, ?, ?, ?, ?, ?, ?)
    ");

    $insertStmt->execute([
        $bookingId,
        $receiptNo,
        $balanceAmount,
        $paymentStatus,
        $loggedInUserId,
        $customerName,
        $contactNumber,
        $parkingLocation,
        $vehicleNumber,
        $expectedParkingDuration,
        $realArrivedAt
    ]);

    $receiptId = $conn->lastInsertId();

    // get generated by name
    $userStmt = $conn->prepare("SELECT name FROM users WHERE id = ?");
    $userStmt->execute([$loggedInUserId]);
    $user = $userStmt->fetch(PDO::FETCH_ASSOC);
    $generatedByName = $user['name'] ?? ('User ID ' . $loggedInUserId);

    // company details
    $companyName = 'Airport Parking';
    $companyAddress = 'No. 371/5, Negombo Road, Seeduwa, Sri Lanka';
    $companyContact = 'info@airportparking.lk | +94 76 141 4557';

    // logo optional
    $logoPath = dirname(__DIR__, 2) . '/assets/img/logo.png';
    $logoDataUri = '';
    if (file_exists($logoPath)) {
        $logoType = pathinfo($logoPath, PATHINFO_EXTENSION);
        $logoData = file_get_contents($logoPath);
        $logoDataUri = 'data:image/' . $logoType . ';base64,' . base64_encode($logoData);
    }

    $generatedAtFormatted = date('d M Y, h:i A');

    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @page { size: A4 portrait; margin: 10mm; }
            body { font-family: DejaVu Sans, Arial, sans-serif; color: #1f2937; font-size: 12px; margin: 0; }
            .receipt { border: 1px solid #d1d5db; border-radius: 10px; overflow: hidden; }
            .header { background: #0f172a; color: #fff; padding: 16px 18px; }
            .header-table, .meta-wrap, .amount-panel, .section-table, .footer-table, .details { width: 100%; border-collapse: collapse; }
            .header-table td, .meta-wrap td, .amount-panel td, .section-table td, .footer-table td { border: none; vertical-align: top; }
            .logo-cell { width: 80px; }
            .logo-box { width: 64px; height: 64px; background: #fff; border-radius: 8px; text-align: center; overflow: hidden; }
            .logo-box img { width: 64px; height: 64px; object-fit: contain; }
            .company-name { font-size: 22px; font-weight: bold; margin: 0 0 4px 0; }
            .company-line { font-size: 11px; margin: 2px 0; color: #e5e7eb; }
            .title-block { text-align: right; }
            .receipt-title { font-size: 24px; font-weight: bold; margin: 0 0 6px 0; }
            .receipt-sub { font-size: 11px; color: #d1d5db; }
            .body { padding: 14px 18px 16px; }
            .meta-wrap td { width: 25%; padding-right: 8px; }
            .meta-card { border: 1px solid #e5e7eb; background: #f8fafc; border-radius: 8px; padding: 10px; }
            .meta-label { font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: bold; margin-bottom: 4px; }
            .meta-value { font-size: 12px; font-weight: bold; color: #111827; }
            .amount-panel { margin: 12px 0 14px; border: 1px solid #dbeafe; background: #eff6ff; }
            .amount-panel td { padding: 14px 16px; }
            .amount-left-title { font-size: 14px; font-weight: bold; color: #1e3a8a; margin-bottom: 4px; }
            .amount-left-sub { font-size: 11px; color: #475569; }
            .amount-right { text-align: right; width: 220px; }
            .amount-label { font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: bold; margin-bottom: 3px; }
            .amount-value { font-size: 26px; font-weight: bold; color: #111827; }
            .paid-badge { display: inline-block; padding: 5px 10px; font-size: 10px; font-weight: bold; color: #166534; background: #dcfce7; border: 1px solid #bbf7d0; border-radius: 20px; margin-top: 6px; }
            .section-table td { width: 50%; padding-right: 8px; }
            .section-box { border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
            .section-title { background: #f3f4f6; color: #111827; font-size: 11px; font-weight: bold; text-transform: uppercase; padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
            .details td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
            .details tr:last-child td { border-bottom: none; }
            .details td:first-child { width: 42%; font-weight: bold; color: #374151; background: #fafafa; }
            .footer { margin-top: 14px; border-top: 1px dashed #cbd5e1; padding-top: 10px; }
            .footer-note { font-size: 10px; color: #6b7280; line-height: 1.5; width: 60%; }
            .signature-box { width: 220px; text-align: center; }
            .signature-line { border-top: 1px solid #111827; margin-top: 34px; margin-bottom: 5px; }
            .signature-name { font-size: 11px; font-weight: bold; color: #111827; }
            .signature-role { font-size: 10px; color: #6b7280; }
        </style>
    </head>
    <body>
        <div class="receipt">
            <div class="header">
                <table class="header-table">
                    <tr>
                        <td class="logo-cell">
                            <?php if ($logoDataUri): ?>
                                <div class="logo-box"><img src="<?= $logoDataUri ?>" alt="Logo"></div>
                            <?php endif; ?>
                        </td>
                        <td>
                            <div class="company-name"><?= h($companyName) ?></div>
                            <div class="company-line"><?= h($companyAddress) ?></div>
                            <div class="company-line"><?= h($companyContact) ?></div>
                        </td>
                        <td class="title-block">
                            <div class="receipt-title">PAYMENT RECEIPT</div>
                            <div class="receipt-sub">Official payment confirmation</div>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="body">
                <table class="meta-wrap">
                    <tr>
                        <td><div class="meta-card"><div class="meta-label">Receipt No</div><div class="meta-value"><?= h($receiptNo) ?></div></div></td>
                        <td><div class="meta-card"><div class="meta-label">Booking Ref</div><div class="meta-value"><?= h($referenceNumber) ?></div></div></td>
                        <td><div class="meta-card"><div class="meta-label">Generated At</div><div class="meta-value"><?= h($generatedAtFormatted) ?></div></div></td>
                        <td><div class="meta-card"><div class="meta-label">Generated By</div><div class="meta-value"><?= h($generatedByName) ?></div></div></td>
                    </tr>
                </table>

                <table class="amount-panel">
                    <tr>
                        <td>
                            <div class="amount-left-title">Payment successfully collected</div>
                            <div class="amount-left-sub">This receipt confirms the collected amount for the related Airport Parking booking.</div>
                            <div class="paid-badge"><?= h($paymentStatus) ?></div>
                        </td>
                        <td class="amount-right">
                            <div class="amount-label">Payment Amount</div>
                            <div class="amount-value">LKR <?= number_format($balanceAmount, 2) ?></div>
                        </td>
                    </tr>
                </table>

                <table class="section-table">
                    <tr>
                        <td>
                            <div class="section-box">
                                <div class="section-title">Customer Details</div>
                                <table class="details">
                                    <tr><td>Customer Name</td><td><?= h($customerName) ?></td></tr>
                                    <tr><td>Contact Number</td><td><?= h($contactNumber) ?></td></tr>
                                    <tr><td>Vehicle Number</td><td><?= h($vehicleNumber) ?></td></tr>
                                    
                                </table>
                            </div>
                        </td>
                        <td>
                            <div class="section-box">
                                <div class="section-title">Receipt Details</div>
                                <table class="details">
                                    <tr><td>Receipt Number</td><td><?= h($receiptNo) ?></td></tr>
                                    <tr><td>Booking Reference</td><td><?= h($referenceNumber) ?></td></tr>
                                    <tr><td>Parking Duration</td><td><?= h($expectedParkingDuration) ?></td></tr>
                                    <tr><td>System Date & Time</td><td><?= h($generatedAtFormatted) ?></td></tr>
                                </table>
                            </div>
                        </td>
                    </tr>
                </table>

                <div class="footer">
                    <table class="footer-table">
                        <tr>
                            <td class="footer-note">
                                This is a system-generated receipt issued by <?= h($companyName) ?>.
                                Please retain this document for your records and future reference.
                            </td>
                            <td class="signature-box">
                                <div class="signature-line"></div>
                                <div class="signature-name"><?= h($companyName) ?></div>
                                <div class="signature-role">Authorized Signature</div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </body>
    </html>
    <?php
    $pdfHtml = ob_get_clean();

    $options = new Options();
    $options->set('isRemoteEnabled', true);

    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdfHtml);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    // save PDF to folder: /payment-receipts/{reference_number}/
    $safeReference = safeFolderName($referenceNumber);
    $relativeFolder = 'payment-receipts/' . $safeReference;
    $absoluteFolder = dirname(__DIR__, 2) . '/' . $relativeFolder;

    if (!is_dir($absoluteFolder)) {
        mkdir($absoluteFolder, 0777, true);
    }

    $fileName = 'receipt_' . $receiptNo . '.pdf';
    $absoluteFilePath = $absoluteFolder . '/' . $fileName;
    $relativeFilePath = $relativeFolder . '/' . $fileName;

    file_put_contents($absoluteFilePath, $dompdf->output());

    $pathStmt = $conn->prepare("
        UPDATE payment_receipts
        SET receipt_path = ?
        WHERE id = ?
    ");
    $pathStmt->execute([$relativeFilePath, $receiptId]);

    $conn->commit();

    echo json_encode([
        'success' => true,
        'receipt_id' => $receiptId,
        'balance_amount' => $balanceAmount,
        'receipt_path' => $relativeFilePath
    ]);
} catch (Throwable $e) {
    if ($conn->inTransaction()) {
        $conn->rollBack();
    }

    echo json_encode([
        'success' => false,
        'message' => 'Error generating receipt: ' . $e->getMessage()
    ]);
}