<?php
require_once __DIR__ . '/db_connect.php';

$bookingId = $_GET['booking_id'] ?? null;
if (!$bookingId) exit('Invalid request');

try {
    $stmtBooking = $conn->prepare("
        SELECT 
            id,
            reference_number,
            name,
            whatsapp_number,
            vehicle_number,
            slot_number
        FROM reserved_slots
        WHERE id = ?
    ");
    $stmtBooking->execute([$bookingId]);
    $booking = $stmtBooking->fetch(PDO::FETCH_ASSOC);

    if (!$booking) exit('Booking not found');

    $stmt = $conn->prepare("
        SELECT 
            pr.*,
            u.name AS generated_by_name
        FROM payment_receipts pr
        LEFT JOIN users u ON u.id = pr.generated_by
        WHERE pr.reserved_slot_id = ?
        ORDER BY pr.generated_at DESC
    ");
    $stmt->execute([$bookingId]);
    $receipts = $stmt->fetchAll(PDO::FETCH_ASSOC);

} catch (PDOException $e) {
    exit('Database error');
}

function webPath($path) {
    if (!$path) return null;

    $path = str_replace('\\', '/', $path);

    if (preg_match('#^https?://#i', $path)) return $path;

    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';

    return $protocol . '://' . $_SERVER['HTTP_HOST'] . '/' . ltrim($path, '/');
}
?>

<div class="modal-header">
    <h5 class="modal-title fw-bold">
        Receipt History – <?= htmlspecialchars($booking['reference_number']) ?>
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>

<div class="modal-body">

    <div class="mb-3">
        <strong>Customer:</strong> <?= htmlspecialchars($booking['name']) ?> |
        <strong>Vehicle:</strong> <?= htmlspecialchars($booking['vehicle_number']) ?> |
        <strong>Contact:</strong> <?= htmlspecialchars($booking['whatsapp_number']) ?>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Receipt No</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Date</th>
                    <th>Generated By</th>
                    <th>PDF</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($receipts): ?>
                    <?php foreach ($receipts as $i => $r): ?>
                        <tr>
                            <td><?= $i + 1 ?></td>
                            <td><?= htmlspecialchars($r['receipt_no']) ?></td>
                            <td>LKR <?= number_format($r['payment_amount'], 2) ?></td>
                            <td>
                                <span class="badge bg-success">
                                    <?= htmlspecialchars($r['payment_status']) ?>
                                </span>
                            </td>
                            <td><?= date('d M Y h:i A', strtotime($r['generated_at'])) ?></td>
                            <td><?= htmlspecialchars($r['generated_by_name']) ?></td>
                            <td>
                                <?php if (!empty($r['receipt_path'])): ?>
                                    <a href="<?= webPath($r['receipt_path']) ?>" target="_blank" class="btn btn-sm btn-primary">
                                        Open PDF
                                    </a>
                                <?php else: ?>
                                    N/A
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="7" class="text-center">No receipts found</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>

</div>

<div class="modal-footer">
    <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>